public class FERPRequestWrapper { 
    @AuraEnabled
    public String ClaimName {set;get;}
    @AuraEnabled
    public Date Service_Start_Date {set;get;}
    @AuraEnabled
    public Date Service_End_Date {set;get;}
    @AuraEnabled
    public String Requestor_First_Name {set;get;} 
    @AuraEnabled
    public String Requestor_Middle_Name {set;get;}
    @AuraEnabled
    public String Requestor_Last_Name {set;get;}
    @AuraEnabled
    public String Requestor_Phone {set;get;}
    @AuraEnabled
    public String Requestor_State {set;get;}
    @AuraEnabled
    public String Requestor_Apt {set;get;}
    @AuraEnabled
    public String Requestor_City {set;get;}
    @AuraEnabled
    public String Requestor_County {set;get;}
    @AuraEnabled
    public String Requestor_Email {set;get;}
    @AuraEnabled
    public String Requestor_Fax {set;get;}
    @AuraEnabled
    public String Requestor_Street {set;get;}
    @AuraEnabled
    public String Requestor_Zip {set;get;}
    @AuraEnabled
    public String Age {set;get;}
    @AuraEnabled
    public String Claimant_Apt {set;get;}
    @AuraEnabled
    public String Claimant_City {set;get;}
    @AuraEnabled
    public String Claimant_County {set;get;}
    @AuraEnabled
    public String Claimant_Email {set;get;}
    @AuraEnabled
    public String Claimant_Fax {set;get;}
    @AuraEnabled
    public String Claimant_First_Name {set;get;}
    @AuraEnabled
    public String Claimant_Last_Name {set;get;}
    @AuraEnabled
    public String Claimant_Middle_Name {set;get;}
    @AuraEnabled
    public String Claimant_Phone {set;get;}
    @AuraEnabled
    public String Claimant_State {set;get;}
    @AuraEnabled
    public String Claimant_Street {set;get;}
    @AuraEnabled
    public String Claimant_Zip {set;get;}
    @AuraEnabled
    public String Health_Plan {set;get;}
    @AuraEnabled
    public String Health_Plan_Entity_Id {set;get;}
    @AuraEnabled
    public String Health_Plan_Entity_AddressId {set;get;}
    @AuraEnabled
    public String Health_Plan_Apt {set;get;}
    @AuraEnabled
    public String Health_Plan_City {set;get;}
    @AuraEnabled
    public String Health_Plan_Fax {set;get;}
    @AuraEnabled
    public String Health_Plan_Phone {set;get;}
    @AuraEnabled
    public String Health_Plan_State {set;get;}
    @AuraEnabled
    public String Health_Plan_Street {set;get;}
    @AuraEnabled
    public String Health_Plan_Zip {set;get;}
    @AuraEnabled
    public String Provider_ferp {set;get;}
    @AuraEnabled
    public Boolean Expedite_Selected {set;get;}
    @AuraEnabled
    public String Denial_Reason {set;get;}
    @AuraEnabled
    public String Final_Denial_Date {set;get;}
    @AuraEnabled
    public String Denial_Notic_Attached {set;get;}
    @AuraEnabled
    public String Denial_Disagreement_Reason {set;get;}
    @AuraEnabled
    public String Expedite_Reason {set;get;}
    @AuraEnabled
    public String Policy_Holder_Apt {set;get;}
    @AuraEnabled
    public String Policy_Holder_City {set;get;}
    @AuraEnabled
    public String Policy_Holder_County {set;get;}
    @AuraEnabled
    public String Policy_Holder_Email {set;get;}
    @AuraEnabled
    public String Policy_Holder_Fax {set;get;}
    @AuraEnabled
    public String Policy_First_Name {set;get;}
    @AuraEnabled
    public String Policy_Holder_Insurance_ID {set;get;}
    @AuraEnabled
    public String Policy_Holder_Last_Name {set;get;}
    @AuraEnabled
    public String Policy_Holder_Middle_Name {set;get;}
    @AuraEnabled
    public String Policy_Holder_Phone {set;get;}
    @AuraEnabled
    public String Policy_Holder_State {set;get;}
    @AuraEnabled
    public String Policy_Holder_Street {set;get;}
    @AuraEnabled
    public String Policy_Holder_Zip {set;get;}
    @AuraEnabled
    public String Reason_for_Review {set;get;}
}